version: "3.7"

services:
  app:
    image: "quay.io/upennlibraries/vceditor_web:${RELEASE_TAG}"
    command: server -b 0.0.0.0
    environment:
      - ADMIN_EMAIL
      - APPLICATION_HOST
      - MAILER_DEFAULT_FROM
      - MAILER_DOMAIN
      - MAILER_HOST
      - MAILER_PORT
      - MAILER_PWD
      - MAILER_USR
      - PROJECT_URL
      - RAILS_ENV
      - RAILS_SERVE_STATIC_FILES
      - RELEASE_TAG
      - SECRET_KEY_BASE
      - XPROC_URL
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${INSTANCE}-app.rule=Host(`${PROJECT_URL}`)"
        - "traefik.http.routers.${INSTANCE}-app.entrypoints=${INSTANCE}"
        - "traefik.http.services.${INSTANCE}-app.loadbalancer.server.port=3000"
    networks:
      - internal
      - traefik

  mongo:
    image: mongo:4.0
    volumes:
      - db:/data/db
    networks:
      - internal

  xproc:
    image: "quay.io/upennlibraries/vceditor_idrovora:${RELEASE_TAG}"
    command: --http 2000 --http-context-path /xproc --http-doc-root /docs /xpl
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${INSTANCE}-xproc.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/xproc`)"
        - "traefik.http.routers.${INSTANCE}-xproc.entrypoints=${INSTANCE}"
        - "traefik.http.services.${INSTANCE}-xproc.loadbalancer.server.port=2000"
    networks:
      - internal
      - traefik
    volumes:
      - xproc:/docs

networks:
  internal:
  traefik:
    external: true

volumes:
  db:
    name: ${INSTANCE}-db
  xproc:
    name: ${INSTANCE}-xproc
